### ISSUE TITLE
Add Kupo "restore script"

### ISSUE THREAD

**Issue by albertodvp** [mlabs-haskell/cardanow#46]
Follow the approach used here for `cardano-node`: https://github.com/mlabs-haskell/cardanow/blob/master/components/cardano-node/Dockerfile
to make kupo snapshots usable.

The script (docker image) depends on some connection to a local cardano-node in order to receive information from the blockchain (basically the dependency Kupo has https://cardanosolutions.github.io/kupo/#section/Getting-started)

**Comment by aciceri** [comment]
Recapping what we agreed during the meeting:
- we don't want to create new docker images that wrap upstream ones, it will be too opinionated and this way we'll not have to maintain images (and pushing them)
- we'll provide a single `docker-compose.yaml` file that will act as an easy cardanow example of use by simply starting upstream docker container services and accordingly mounting our extracted snapshots
- this `docker-compose.yaml` will also define another container that will be our fetch script (basically `wget`+`tar` from our bucket)
- this fetch script needs to be parametrizable (consumers may need only a subset of services), in our `docker-compose.yaml` we'll fetch all the snapshots
- our fetch container will be a "one shot container" and all other services will depend on it

Just a not working sketch:
```yaml
services:
  cardanow-fetch:
    build:
      context: .foo/ # this directory will contain the script itself
      dockerfile: ./foo/Dockerfile
    environment:
        # here we parametrize services we want to fetch snapshots for
        - CARDANO_NODE=true
        - KUPO=true

  cardano-node:
    image: official-cardano-node
    volumes:
      - cardano-node-state:/var/lib/cardano-node
    depends_on:
      cardanow-fetch:
        condition: service_completed_successfully

  kupo:
    image: official-kupo
    volumes:
      - kupo-state:/var/lib/kupo
    depends_on:
      cardanow-fetch:
        condition: service_completed_successfully
  
  # etc...

volumes:
  cardano-node-state:
  kupo-state:
  # etc...
```

It would be nice if the `cardanow-fetch` was pushed somewhere, we could re-use the dockerhub pipeline (or use nix to build it and and an ad-hoc Hercules CI effect to push it somewhere)

cc @albertodvp
